---
kind: pipeline
type: docker
name: verify
steps:
- name: test
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm install
  - npm test
trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: release
steps:
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
trigger:
  event:
    - tag
---
kind: secret
name: npm_access_token
data: s4Tbcz0z4nzUJnbo01DsCJKDNNiGt2okAxAEF8CUJQdb5rzDg6WGlnmmGfQlN6tBFXuVD5LO4xwnpy0bbhNiOrUXXzk=
---
kind: signature
hmac: ceb3824d54252c6c3e9148bee30ea6954ec543fdc982dfe1e44b41d1a502b370

...
